### ISSUE TITLE
Ошибка при вызове функции rpcf_search_users_lite

### ISSUE THREAD

**Issue by big-town** [k-shym/URFAClient#13]
Version:5.2.1-009-update2
```xml
<function name="rpcf_search_users_lite" id="0x1202">
    <input>
      <string name="login" />
      <string name="email" />
      <string name="fname" />
    </input>
    <output>
      <integer name="success" />
      <integer name="total" />
      <integer name="show_count" />
      <if variable="show_count" value="0" condition="ne">
        <for name="i" from="0" count="show_count">
          <integer name="id" array_index="i" />
          <string name="login" array_index="i" />
          <string name="email" array_index="i" />
          <string name="name" array_index="i" />
        </for>
      </if>
    </output>
  </function>```

Если пользователь найден, то возникает ошибка:

 ```PHP Fatal error:  Uncaught exception 'Exception' with message 'Not provided an error, contact the developer (_proccess_data_output)' in /MYUTM/ORFA_xmp/URFAClient/classes/URFAClient/API.php:315
 Stack trace:
 #0 /MYUTM/ORFA_xmp/URFAClient/classes/URFAClient/API.php(304): URFAClient_API-_proccess_data_output(Object(SimpleXMLElement), Object(URFAClient_Packet))
 #1 /MYUTM/ORFA_xmp/URFAClient/classes/URFAClient/API.php(95): URFAClient_API-_proccess_data_output(Object(SimpleXMLElement), Object(URFAClient_Packet))
 #2 /MYUTM/ORFA_xmp/rpcf_search_users_lite.php(16): URFAClient_API->__call('rpcf_search_use...', Array)
 #3 /MYUTM/ORFA_xmp/rpcf_search_users_lite.php(16): URFAClient_API-rpcf_search_users_lite(Array)
 #4 {main}
  thrown in /MYUTM/ORFA_xmp/URFAClient/classes/URFAClient/API.php on line 315
```
Если не найден, то возвращается результат вида:

```php
  array(3) {
   ["success"]=>
   int(0)
   ["total"]=>
   int(0)
   ["show_count"]=>
   int(0)
 }

**Comment by k-shym** [comment]
В следующей версии я учту этот момент. Как временное решение, уберите в описании функции условие `<if variable="show_count" value="0" condition="ne">`.

**Comment by big-town** [comment]
Вы меня неправильно поняли, ошибка возникает как раз когда функция возвращает данные.

**Comment by big-town** [comment]
Вот здесь, в другом проекте, обсуждалась эта проблема http://www.netup.ru/phpbb/viewtopic.php?p=40567, исправленная функция оттуда работает.
Возвращает данные вида:

```php
 Array
(
    [success] => 0
    [total] => 1
    [show_count] => 1
    [list] => Array
        (
            [0] => Array
                (
                    [id] => 9949
                    [login] => RKN
                    [email] => 
                    [fname] => рос ком надзор
                )

        )

)

**Comment by k-shym** [comment]
Функция описана нестандартно. Пожалуйста, попробуйте сделать, как я написал выше.

**Comment by big-town** [comment]
Ну да сработало. То есть исключение генерируется во время условия?

**Comment by k-shym** [comment]
Логика обработки такая, что перед циклом **for** должен идти счетчик **integer**, а в Вашем случае там условие которое не нужно, т.к. если в счетчике вернется 0, то цикл не выполнится. Поэтому генерируется мое исключение _Not provided an error, contact the developer (proccess_data_output)_ В следующей версии изменю условия обработки и проблемы не будет, и после закрою данный вопрос.

**Comment by k-shym** [comment]
Теперь данный момент учитывается.
