### ISSUE TITLE
rpcf_get_iptraffic_service не работает с UTM 5.5-006

### ISSUE THREAD

**Issue by abaurin** [k-shym/URFAClient#40]
Добрый день !

Не получается получить вывод функции rpcf_get_iptraffic_service с UTM 5.5-006
При этом rpcf_get_iptraffic_service_ex работает

Выдает следующее:

```
PHP Warning:  unpack(): Type N: not enough input, need 4, have 0 in /home/balu/utm-work/sms/URFAClient/classes/URFAClient/Packet.php on line 256
PHP Stack trace:
PHP   1. {main}() /home/balu/utm-work/sms/sms-shaper.php:0
PHP   2. URFAClient_API->rpcf_get_iptraffic_service() /home/balu/utm-work/sms/sms-shaper.php:150
PHP   3. URFAClient_API->__call() /home/balu/utm-work/sms/sms-shaper.php:150
PHP   4. URFAClient_API->processDataOutput() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/API.php:129
PHP   5. URFAClient_API->processDataOutput() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/API.php:433
PHP   6. URFAClient_API->processDataOutput() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/API.php:404
PHP   7. URFAClient_API->processDataOutput() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/API.php:433
PHP   8. URFAClient_Packet->getDataLong() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/API.php:325
PHP   9. unpack() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/Packet.php:256
PHP Warning:  unpack(): Type d: not enough input, need 8, have 4 in /home/balu/utm-work/sms/URFAClient/classes/URFAClient/Packet.php on line 154
PHP Stack trace:
PHP   1. {main}() /home/balu/utm-work/sms/sms-shaper.php:0
PHP   2. URFAClient_API->rpcf_get_iptraffic_service() /home/balu/utm-work/sms/sms-shaper.php:150
PHP   3. URFAClient_API->__call() /home/balu/utm-work/sms/sms-shaper.php:150
PHP   4. URFAClient_API->processDataOutput() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/API.php:129
PHP   5. URFAClient_API->processDataOutput() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/API.php:433
PHP   6. URFAClient_API->processDataOutput() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/API.php:404
PHP   7. URFAClient_API->processDataOutput() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/API.php:433
PHP   8. URFAClient_Packet->getDataDouble() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/API.php:328
PHP   9. unpack() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/Packet.php:154
PHP Warning:  unpack(): Type N: not enough input, need 4, have 0 in /home/balu/utm-work/sms/URFAClient/classes/URFAClient/Packet.php on line 256
PHP Stack trace:
PHP   1. {main}() /home/balu/utm-work/sms/sms-shaper.php:0
PHP   2. URFAClient_API->rpcf_get_iptraffic_service() /home/balu/utm-work/sms/sms-shaper.php:150
PHP   3. URFAClient_API->__call() /home/balu/utm-work/sms/sms-shaper.php:150
PHP   4. URFAClient_API->processDataOutput() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/API.php:129
PHP   5. URFAClient_API->processDataOutput() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/API.php:433
PHP   6. URFAClient_API->processDataOutput() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/API.php:404
PHP   7. URFAClient_API->processDataOutput() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/API.php:433
PHP   8. URFAClient_Packet->getDataLong() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/API.php:325
PHP   9. unpack() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/Packet.php:256
PHP Warning:  unpack(): Type d: not enough input, need 8, have 4 in /home/balu/utm-work/sms/URFAClient/classes/URFAClient/Packet.php on line 154
PHP Stack trace:
PHP   1. {main}() /home/balu/utm-work/sms/sms-shaper.php:0
PHP   2. URFAClient_API->rpcf_get_iptraffic_service() /home/balu/utm-work/sms/sms-shaper.php:150
PHP   3. URFAClient_API->__call() /home/balu/utm-work/sms/sms-shaper.php:150
PHP   4. URFAClient_API->processDataOutput() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/API.php:129
PHP   5. URFAClient_API->processDataOutput() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/API.php:433
PHP   6. URFAClient_API->processDataOutput() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/API.php:404
PHP   7. URFAClient_API->processDataOutput() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/API.php:433
PHP   8. URFAClient_Packet->getDataDouble() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/API.php:328
PHP   9. unpack() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/Packet.php:154
PHP Warning:  unpack(): Type N: not enough input, need 4, have 0 in /home/balu/utm-work/sms/URFAClient/classes/URFAClient/Packet.php on line 256
PHP Stack trace:
PHP   1. {main}() /home/balu/utm-work/sms/sms-shaper.php:0
PHP   2. URFAClient_API->rpcf_get_iptraffic_service() /home/balu/utm-work/sms/sms-shaper.php:150
PHP   3. URFAClient_API->__call() /home/balu/utm-work/sms/sms-shaper.php:150
PHP   4. URFAClient_API->processDataOutput() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/API.php:129
PHP   5. URFAClient_API->processDataOutput() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/API.php:433
PHP   6. URFAClient_API->processDataOutput() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/API.php:404
PHP   7. URFAClient_API->processDataOutput() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/API.php:433
PHP   8. URFAClient_Packet->getDataLong() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/API.php:325
PHP   9. unpack() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/Packet.php:256
PHP Warning:  unpack(): Type d: not enough input, need 8, have 4 in /home/balu/utm-work/sms/URFAClient/classes/URFAClient/Packet.php on line 154
PHP Stack trace:
PHP   1. {main}() /home/balu/utm-work/sms/sms-shaper.php:0
PHP   2. URFAClient_API->rpcf_get_iptraffic_service() /home/balu/utm-work/sms/sms-shaper.php:150
PHP   3. URFAClient_API->__call() /home/balu/utm-work/sms/sms-shaper.php:150
PHP   4. URFAClient_API->processDataOutput() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/API.php:129
PHP   5. URFAClient_API->processDataOutput() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/API.php:433
PHP   6. URFAClient_API->processDataOutput() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/API.php:404
PHP   7. URFAClient_API->processDataOutput() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/API.php:433
PHP   8. URFAClient_Packet->getDataDouble() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/API.php:328
PHP   9. unpack() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/Packet.php:154
PHP Warning:  unpack(): Type N: not enough input, need 4, have 0 in /home/balu/utm-work/sms/URFAClient/classes/URFAClient/Packet.php on line 256
PHP Stack trace:
PHP   1. {main}() /home/balu/utm-work/sms/sms-shaper.php:0
PHP   2. URFAClient_API->rpcf_get_iptraffic_service() /home/balu/utm-work/sms/sms-shaper.php:150
PHP   3. URFAClient_API->__call() /home/balu/utm-work/sms/sms-shaper.php:150
PHP   4. URFAClient_API->processDataOutput() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/API.php:129
PHP   5. URFAClient_API->processDataOutput() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/API.php:433
PHP   6. URFAClient_API->processDataOutput() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/API.php:404
PHP   7. URFAClient_API->processDataOutput() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/API.php:433
PHP   8. URFAClient_Packet->getDataLong() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/API.php:325
PHP   9. unpack() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/Packet.php:256
PHP Warning:  unpack(): Type d: not enough input, need 8, have 4 in /home/balu/utm-work/sms/URFAClient/classes/URFAClient/Packet.php on line 154
PHP Stack trace:
PHP   1. {main}() /home/balu/utm-work/sms/sms-shaper.php:0
PHP   2. URFAClient_API->rpcf_get_iptraffic_service() /home/balu/utm-work/sms/sms-shaper.php:150
PHP   3. URFAClient_API->__call() /home/balu/utm-work/sms/sms-shaper.php:150
PHP   4. URFAClient_API->processDataOutput() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/API.php:129
PHP   5. URFAClient_API->processDataOutput() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/API.php:433
PHP   6. URFAClient_API->processDataOutput() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/API.php:404
PHP   7. URFAClient_API->processDataOutput() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/API.php:433
PHP   8. URFAClient_Packet->getDataDouble() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/API.php:328
PHP   9. unpack() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/Packet.php:154
PHP Warning:  unpack(): Type N: not enough input, need 4, have 0 in /home/balu/utm-work/sms/URFAClient/classes/URFAClient/Packet.php on line 256
PHP Stack trace:
PHP   1. {main}() /home/balu/utm-work/sms/sms-shaper.php:0
PHP   2. URFAClient_API->rpcf_get_iptraffic_service() /home/balu/utm-work/sms/sms-shaper.php:150
PHP   3. URFAClient_API->__call() /home/balu/utm-work/sms/sms-shaper.php:150
PHP   4. URFAClient_API->processDataOutput() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/API.php:129
PHP   5. URFAClient_API->processDataOutput() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/API.php:433
PHP   6. URFAClient_API->processDataOutput() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/API.php:404
PHP   7. URFAClient_API->processDataOutput() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/API.php:433
PHP   8. URFAClient_Packet->getDataLong() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/API.php:325
PHP   9. unpack() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/Packet.php:256
PHP Warning:  unpack(): Type d: not enough input, need 8, have 4 in /home/balu/utm-work/sms/URFAClient/classes/URFAClient/Packet.php on line 154
PHP Stack trace:
PHP   1. {main}() /home/balu/utm-work/sms/sms-shaper.php:0
PHP   2. URFAClient_API->rpcf_get_iptraffic_service() /home/balu/utm-work/sms/sms-shaper.php:150
PHP   3. URFAClient_API->__call() /home/balu/utm-work/sms/sms-shaper.php:150
PHP   4. URFAClient_API->processDataOutput() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/API.php:129
PHP   5. URFAClient_API->processDataOutput() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/API.php:433
PHP   6. URFAClient_API->processDataOutput() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/API.php:404
PHP   7. URFAClient_API->processDataOutput() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/API.php:433
PHP   8. URFAClient_Packet->getDataDouble() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/API.php:328
PHP   9. unpack() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/Packet.php:154
PHP Warning:  unpack(): Type N: not enough input, need 4, have 0 in /home/balu/utm-work/sms/URFAClient/classes/URFAClient/Packet.php on line 256
PHP Stack trace:
PHP   1. {main}() /home/balu/utm-work/sms/sms-shaper.php:0
PHP   2. URFAClient_API->rpcf_get_iptraffic_service() /home/balu/utm-work/sms/sms-shaper.php:150
PHP   3. URFAClient_API->__call() /home/balu/utm-work/sms/sms-shaper.php:150
PHP   4. URFAClient_API->processDataOutput() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/API.php:129
PHP   5. URFAClient_API->processDataOutput() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/API.php:433
PHP   6. URFAClient_API->processDataOutput() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/API.php:404
PHP   7. URFAClient_API->processDataOutput() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/API.php:433
PHP   8. URFAClient_Packet->getDataLong() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/API.php:325
PHP   9. unpack() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/Packet.php:256
PHP Warning:  unpack(): Type d: not enough input, need 8, have 4 in /home/balu/utm-work/sms/URFAClient/classes/URFAClient/Packet.php on line 154
PHP Stack trace:
PHP   1. {main}() /home/balu/utm-work/sms/sms-shaper.php:0
PHP   2. URFAClient_API->rpcf_get_iptraffic_service() /home/balu/utm-work/sms/sms-shaper.php:150
PHP   3. URFAClient_API->__call() /home/balu/utm-work/sms/sms-shaper.php:150
PHP   4. URFAClient_API->processDataOutput() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/API.php:129
PHP   5. URFAClient_API->processDataOutput() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/API.php:433
PHP   6. URFAClient_API->processDataOutput() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/API.php:404
PHP   7. URFAClient_API->processDataOutput() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/API.php:433
PHP   8. URFAClient_Packet->getDataDouble() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/API.php:328
PHP   9. unpack() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/Packet.php:154
PHP Notice:  Undefined offset: 29 in /home/balu/utm-work/sms/URFAClient/classes/URFAClient/Packet.php on line 256
PHP Stack trace:
PHP   1. {main}() /home/balu/utm-work/sms/sms-shaper.php:0
PHP   2. URFAClient_API->rpcf_get_iptraffic_service() /home/balu/utm-work/sms/sms-shaper.php:150
PHP   3. URFAClient_API->__call() /home/balu/utm-work/sms/sms-shaper.php:150
PHP   4. URFAClient_API->processDataOutput() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/API.php:129
PHP   5. URFAClient_API->processDataOutput() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/API.php:433
PHP   6. URFAClient_API->processDataOutput() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/API.php:404
PHP   7. URFAClient_API->processDataOutput() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/API.php:433
PHP   8. URFAClient_Packet->getDataLong() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/API.php:325
PHP Warning:  unpack(): Type N: not enough input, need 4, have 0 in /home/balu/utm-work/sms/URFAClient/classes/URFAClient/Packet.php on line 256
PHP Stack trace:
PHP   1. {main}() /home/balu/utm-work/sms/sms-shaper.php:0
PHP   2. URFAClient_API->rpcf_get_iptraffic_service() /home/balu/utm-work/sms/sms-shaper.php:150
PHP   3. URFAClient_API->__call() /home/balu/utm-work/sms/sms-shaper.php:150
PHP   4. URFAClient_API->processDataOutput() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/API.php:129
PHP   5. URFAClient_API->processDataOutput() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/API.php:433
PHP   6. URFAClient_API->processDataOutput() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/API.php:404
PHP   7. URFAClient_API->processDataOutput() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/API.php:433
PHP   8. URFAClient_Packet->getDataLong() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/API.php:325
PHP   9. unpack() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/Packet.php:256
PHP Notice:  Undefined offset: 30 in /home/balu/utm-work/sms/URFAClient/classes/URFAClient/Packet.php on line 154
PHP Stack trace:
PHP   1. {main}() /home/balu/utm-work/sms/sms-shaper.php:0
PHP   2. URFAClient_API->rpcf_get_iptraffic_service() /home/balu/utm-work/sms/sms-shaper.php:150
PHP   3. URFAClient_API->__call() /home/balu/utm-work/sms/sms-shaper.php:150
PHP   4. URFAClient_API->processDataOutput() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/API.php:129
PHP   5. URFAClient_API->processDataOutput() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/API.php:433
PHP   6. URFAClient_API->processDataOutput() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/API.php:404
PHP   7. URFAClient_API->processDataOutput() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/API.php:433
PHP   8. URFAClient_Packet->getDataDouble() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/API.php:328
PHP Warning:  unpack(): Type d: not enough input, need 8, have 0 in /home/balu/utm-work/sms/URFAClient/classes/URFAClient/Packet.php on line 154
PHP Stack trace:
PHP   1. {main}() /home/balu/utm-work/sms/sms-shaper.php:0
PHP   2. URFAClient_API->rpcf_get_iptraffic_service() /home/balu/utm-work/sms/sms-shaper.php:150
PHP   3. URFAClient_API->__call() /home/balu/utm-work/sms/sms-shaper.php:150
PHP   4. URFAClient_API->processDataOutput() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/API.php:129
PHP   5. URFAClient_API->processDataOutput() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/API.php:433
PHP   6. URFAClient_API->processDataOutput() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/API.php:404
PHP   7. URFAClient_API->processDataOutput() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/API.php:433
PHP   8. URFAClient_Packet->getDataDouble() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/API.php:328
PHP   9. unpack() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/Packet.php:154
PHP Notice:  Undefined offset: 31 in /home/balu/utm-work/sms/URFAClient/classes/URFAClient/Packet.php on line 256
PHP Stack trace:
PHP   1. {main}() /home/balu/utm-work/sms/sms-shaper.php:0
PHP   2. URFAClient_API->rpcf_get_iptraffic_service() /home/balu/utm-work/sms/sms-shaper.php:150
PHP   3. URFAClient_API->__call() /home/balu/utm-work/sms/sms-shaper.php:150
PHP   4. URFAClient_API->processDataOutput() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/API.php:129
PHP   5. URFAClient_API->processDataOutput() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/API.php:433
PHP   6. URFAClient_API->processDataOutput() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/API.php:404
PHP   7. URFAClient_API->processDataOutput() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/API.php:433
PHP   8. URFAClient_Packet->getDataLong() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/API.php:325
PHP Warning:  unpack(): Type N: not enough input, need 4, have 0 in /home/balu/utm-work/sms/URFAClient/classes/URFAClient/Packet.php on line 256
PHP Stack trace:
PHP   1. {main}() /home/balu/utm-work/sms/sms-shaper.php:0
PHP   2. URFAClient_API->rpcf_get_iptraffic_service() /home/balu/utm-work/sms/sms-shaper.php:150
PHP   3. URFAClient_API->__call() /home/balu/utm-work/sms/sms-shaper.php:150
PHP   4. URFAClient_API->processDataOutput() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/API.php:129
PHP   5. URFAClient_API->processDataOutput() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/API.php:433
PHP   6. URFAClient_API->processDataOutput() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/API.php:404
PHP   7. URFAClient_API->processDataOutput() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/API.php:433
PHP   8. URFAClient_Packet->getDataLong() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/API.php:325
PHP   9. unpack() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/Packet.php:256
PHP Notice:  Undefined offset: 32 in /home/balu/utm-work/sms/URFAClient/classes/URFAClient/Packet.php on line 154
PHP Stack trace:
PHP   1. {main}() /home/balu/utm-work/sms/sms-shaper.php:0
PHP   2. URFAClient_API->rpcf_get_iptraffic_service() /home/balu/utm-work/sms/sms-shaper.php:150
PHP   3. URFAClient_API->__call() /home/balu/utm-work/sms/sms-shaper.php:150
PHP   4. URFAClient_API->processDataOutput() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/API.php:129
PHP   5. URFAClient_API->processDataOutput() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/API.php:433
PHP   6. URFAClient_API->processDataOutput() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/API.php:404
PHP   7. URFAClient_API->processDataOutput() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/API.php:433
PHP   8. URFAClient_Packet->getDataDouble() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/API.php:328
PHP Warning:  unpack(): Type d: not enough input, need 8, have 0 in /home/balu/utm-work/sms/URFAClient/classes/URFAClient/Packet.php on line 154
PHP Stack trace:
PHP   1. {main}() /home/balu/utm-work/sms/sms-shaper.php:0
PHP   2. URFAClient_API->rpcf_get_iptraffic_service() /home/balu/utm-work/sms/sms-shaper.php:150
PHP   3. URFAClient_API->__call() /home/balu/utm-work/sms/sms-shaper.php:150
PHP   4. URFAClient_API->processDataOutput() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/API.php:129
PHP   5. URFAClient_API->processDataOutput() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/API.php:433
PHP   6. URFAClient_API->processDataOutput() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/API.php:404
PHP   7. URFAClient_API->processDataOutput() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/API.php:433
PHP   8. URFAClient_Packet->getDataDouble() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/API.php:328
PHP   9. unpack() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/Packet.php:154
PHP Notice:  Undefined offset: 33 in /home/balu/utm-work/sms/URFAClient/classes/URFAClient/Packet.php on line 129
PHP Stack trace:
PHP   1. {main}() /home/balu/utm-work/sms/sms-shaper.php:0
PHP   2. URFAClient_API->rpcf_get_iptraffic_service() /home/balu/utm-work/sms/sms-shaper.php:150
PHP   3. URFAClient_API->__call() /home/balu/utm-work/sms/sms-shaper.php:150
PHP   4. URFAClient_API->processDataOutput() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/API.php:129
PHP   5. URFAClient_API->processDataOutput() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/API.php:433
PHP   6. URFAClient_Packet->getDataInt() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/API.php:322
PHP Warning:  unpack(): Type N: not enough input, need 4, have 0 in /home/balu/utm-work/sms/URFAClient/classes/URFAClient/Packet.php on line 323
PHP Stack trace:
PHP   1. {main}() /home/balu/utm-work/sms/sms-shaper.php:0
PHP   2. URFAClient_API->rpcf_get_iptraffic_service() /home/balu/utm-work/sms/sms-shaper.php:150
PHP   3. URFAClient_API->__call() /home/balu/utm-work/sms/sms-shaper.php:150
PHP   4. URFAClient_API->processDataOutput() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/API.php:129
PHP   5. URFAClient_API->processDataOutput() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/API.php:433
PHP   6. URFAClient_Packet->getDataInt() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/API.php:322
PHP   7. URFAClient_Packet->bin2int() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/Packet.php:129
PHP   8. unpack() /home/balu/utm-work/sms/URFAClient/classes/URFAClient/Packet.php:323
PHP Fatal error:  Uncaught URFAClient_Exception: Not provided an error, contact the developer (processDataOutput) in /home/balu/utm-work/sms/URFAClient/classes/URFAClient/API.php:392
Stack trace:
#0 /home/balu/utm-work/sms/URFAClient/classes/URFAClient/API.php(433): URFAClient_API->processDataOutput(Object(SimpleXMLElement), Object(URFAClient_Packet))
#1 /home/balu/utm-work/sms/URFAClient/classes/URFAClient/API.php(129): URFAClient_API->processDataOutput(Object(SimpleXMLElement), Object(URFAClient_Packet))
#2 /home/balu/utm-work/sms/sms-shaper.php(150): URFAClient_API->__call('rpcf_get_iptraf...', Array)
#3 {main}
  thrown in /home/balu/utm-work/sms/URFAClient/classes/URFAClient/API.php on line 392
```

Описание самой функции в родном api.xml такое же, как и в предыдущих версиях.
[api_55-006.zip](https://github.com/k-shym/URFAClient/files/6303802/api_55-006.zip)

**Comment by altlc** [comment]
rpcf_get_iptraffic_service_ex тоже не работает, точнее делает вид что работает, давая неправильные данные на выходе, там во первых в xml  неправильное описание, не хватает sheme_id, во вторых в самой библиотеке баг, почему то для циклов for для генерации имени выходного массива и чтения количества элементов этого массива ищется предыдущий элемент типа integer, и из него берутся эти данные. В этих функциях:
```

<for name="i" from="0" count="borders_count">
        <integer name="tclass" array_index="i" />
        <if variable="tclass" value="-1" condition="ne">
          <long name="borders_size" />
          <set dst="borders_size_array" src="borders_size" dst_index="i" />
          <for name="j" from="0" count="borders_size">
            <long name="border_id" array_index="i,j" />
            <double name="border_cost" array_index="i,j" />
          </for>
        </if>
      </for>

```

т.е. количество элементов для чтения в переменной типа long, и как итог библиотека вместо long borders_size берет int  tclass, и читает бред.


Нужно в функции 	protected function processDataOutput(SimpleXMLElement $output, URFAClient_Packet $packet)
сделать так:
```

case 'for':
	$sibling = $node->xpath('preceding-sibling::integer[1]|preceding-sibling::long[1]');

	if (!$sibling) {
	              $sibling = $node->xpath('parent::*[1]/preceding-sibling::integer[1]|parent::*[1]/preceding-sibling::long[1]');

```
Тогда все работает правильно (при условии исправления еще и api.XML)

**Comment by k-shym** [comment]
Привет!

В предыдущих версиях ядра количество элементов в `for` хранилось в `integer`. Сделаю фикс в новой версии, спасибо.

@abaurin @altlc Если есть возможность, пришлите мне на почту ядро UTM 5.5-006 (debian) + utm_admin под эту версию.

**Comment by abaurin** [comment]
@k-shym  Спасибо ! На https://www.netup.tv/en/myutm5plus/downloads уже доступен 5.5-009 Release

**Comment by k-shym** [comment]
@abaurin @altlc спасибо) Исправлено в версии **1.3.5** и для следующего релиза **2.0**
